services:
    netgen_admin_ui.event_listener.set_tags_admin_pagelayout:
        class: Netgen\Bundle\AdminUIBundle\EventListener\SetTagsAdminPageLayoutListener
        arguments:
            - "@eztags.templating.admin_global_variable"
            - "%netgen_admin_ui.tags.pagelayout%"
        # Using siteaccess aware config, so we need the lazy flag
        lazy: true
        calls:
            - [setIsAdminSiteAccess, [$is_admin_ui_siteaccess;netgen_admin_ui$]]
        tags:
            - { name: kernel.event_subscriber }
